controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_base_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_base_controller:
  ros__parameters:
    left_steer_names: ["Steering_Front_Left"]
    left_front_wheel_names: ["Driving_Front_Left"]
    right_steer_names: ["Steering_Front_Right"]
    right_front_wheel_names: ["Driving_Front_Right"]
    left_wheel_names: ["Driving_Left"]
    right_wheel_names: ["Driving_Right"]

    